export function fixture() {
  const now = new Date(),
    date = now.toISOString();
  const ago = (days) => new Date(now.getTime() - days * 86400000).toISOString();
  const rows = {};
  const variants = [
    ["new", "Новая вещь бренда", "Mixed", true, false, 100, 300, 4, 6, "M", 5],
    [
      "used",
      "Бывшая в употреблении вещь",
      "Mixed",
      true,
      true,
      50,
      250,
      3,
      5,
      "XL",
      5,
    ],
    [
      "other",
      "Новая вещь разового поставщика",
      "Other",
      false,
      false,
      80,
      200,
      2,
      3,
      "XXL",
      5,
    ],
    [
      "legacy-new",
      "Старая карточка нового товара",
      "Legacy",
      true,
      undefined,
      100,
      300,
      1,
      1,
      "XS",
      5,
    ],
    [
      "legacy-used",
      "Старая карточка секонда",
      "Legacy",
      false,
      undefined,
      40,
      200,
      1,
      1,
      "XL",
      5,
    ],
    [
      "stale-new",
      "Новый товар 100 дней",
      "Old",
      true,
      false,
      10,
      30,
      2,
      2,
      "S",
      100,
    ],
    [
      "young-used",
      "Секонд 100 дней",
      "Old",
      true,
      true,
      20,
      80,
      2,
      2,
      "XL",
      100,
    ],
    [
      "stale-used",
      "Секонд 130 дней",
      "Old",
      true,
      true,
      30,
      90,
      2,
      2,
      "XL",
      130,
    ],
  ];
  for (const [
    id,
    name,
    brand,
    isPermanentSupplier,
    isSecondhand,
    cost,
    price,
    stock,
    quantity,
    size,
    age,
  ] of variants) {
    rows["products/" + id] = {
      name,
      brand,
      isPermanentSupplier,
      ...(isSecondhand === undefined ? {} : { isSecondhand }),
      cost,
      price,
      stock,
      size,
      article: id,
      category: "Одежда",
      gender: "unisex",
      discount: 0,
      createdAt: ago(age),
    };
    rows["income/" + id] = {
      productId: id,
      productName: name,
      quantity,
      cost,
      totalAmount: cost * quantity,
      date: ago(age),
    };
  }
  for (const [id, productId, quantity, excludeFromStats] of [
    ["one", "new", 2, false],
    ["two", "used", 1, false],
    ["three", "other", 1, false],
    ["excluded", "used", 1, true],
  ]) {
    const p = rows["products/" + productId];
    rows["sales/" + id] = {
      date,
      seller: "Продавец",
      excludeFromStats,
      totalAmount: p.price * quantity,
      items: [
        {
          productId,
          productName: p.name,
          quantity,
          price: p.price,
          total: p.price * quantity,
          priceType: "normal",
        },
      ],
    };
  }
  rows["plans/plan"] = {
    name: "Проверочный план",
    startDate: date.slice(0, 8) + "01",
    endDate: date.slice(0, 8) + "28",
    targetAmount: 2000,
    assignedSeller: "",
    createdAt: date,
  };
  return rows;
}
